name: Test-Notebooks

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  test-notebooks:
    # Name the job
    name: Test Jupyter Notebooks - P4DS
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: p4ds-env-actions
          environment-file: p4ds-env-actions.yml
          python-version: 3.8.8

      - name: Execute all Notebooks
        shell: bash -l {0}
        run: |
          conda activate p4ds-env-actions
          pip install nbmake gdown
          pytest --nbmake
